### ISSUE TITLE
你好，十分感谢你的分享，这里有几个小建议

### ISSUE THREAD

**Issue by Takdrift** [dawangraoming/iconfont-helper-chrome-extension#1]
首先非常感谢作者的分享，这里有几个小建议：

1. 是否可以添加一键清空购物车的选项
2. 若添加的是整个图标库，是否能将现在默认的下载文件名改成相应的图标库名。

再次感谢作者的分享！

**Comment by dawangraoming** [comment]
1、官方默认是有提供“一键清理”的功能，在购物车的右上方；
2、关于名称的功能，目前暂时没有提供，建议使用常用的批量修改文件名的工具，或者统一解压到一个目录来解决这个问题。

感谢反馈❤️

**Comment by dawangraoming** [comment]
close #1
