### ISSUE TITLE
可以不给下载的图标添加数字后缀吗，保持命名的简洁度，谢谢了

### ISSUE THREAD

**Issue by 95junminhuang** [dawangraoming/iconfont-helper-chrome-extension#3]

**Comment by noyobo** [comment]
+1

**Comment by noyobo** [comment]
我自己修改了你 @95junminhuang  可以自行下载并安装

https://github.com/noyobo/iconfont-helper-chrome-extension/releases/tag/v1.2.2

**Comment by 95junminhuang** [comment]
> 我自己修改了你@ 95junminhuang 可以自行下载并安装
> 
> https://github.com/noyobo/iconfont-helper-chrome-extension/releases/tag/v1.2.2
谢谢大佬
